---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: dns64s.network.mingyangtech.com.cn
spec:
  group: network.mingyangtech.com.cn
  names:
    categories:
      - network
    kind: Dns64
    listKind: Dns64List
    plural: dns64s
    singular: dns64
  scope: Namespaced
  versions:
    - additionalPrinterColumns:   
      name: v1
      schema:
        openAPIV3Schema:
          description: Dns64 is the Schema for the Dns64 API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Dns64Spec defines the desired state of Dns64
              properties:
                serviceAddresses:
                  type: array
                  items:
                    type: object
                    properties:
                      serviceAddress:
                        type: string
                      vlan: 
                        type: integer
                forwardDnsList:
                  type: array
                  items:
                    type: string
                compositePrefix:
                  type: string 
                excludedAddresses:
                  type: array
                  items:
                    type: string
                originalIps:
                  type: array
                  items:
                    type: string
                enable:
                  type: boolean    
              required:
                - compositePrefix
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources: {}
