---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: messages.network.mingyangtech.com.cn
spec:
  group: network.mingyangtech.com.cn
  names:
    categories:
      - network
    kind: Message
    listKind: MessageList
    plural: messages
    singular: message
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.account
          name: ACCOUNT
          type: string
        - jsonPath: .spec.pswd
          name: PSWD
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                account:
                  type: string
                pswd:
                  type: string
                msg:
                  type: string
                params:
                  type: string
              required:
                - account
                - pswd
                - params
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources: { }
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: [ ]
  storedVersions: [ ]

